name: Linting

on: [push, pull_request]

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install requirements
        run: |
          set -xe
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt

      - name: Lint with ruff
        run: |
          set -xe
          python -m ruff check
