name: Run Tests

on:
  push:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  COVERAGE_IGOR_VERBOSE: 1
  FORCE_COLOR: 1 # pytest output color

permissions:
  contents: read

jobs:
  test-python:
    name: 'Test Python v${{ matrix.python-version }}'
    runs-on: 'ubuntu-latest'

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.x']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          set -xe
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt

      - name: Test with pytest
        run: |
          set -xe
          python -m pytest -sv

  check:
    if: always()
    name: Tests Successful
    runs-on: ubuntu-latest
    needs: test-python

    steps:
      - name: Whether the whole test suite passed
        uses: re-actors/alls-green@v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
